# Generated by Django 2.1.5 on 2020-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='游戏名字')),
                ('status', models.IntegerField(verbose_name='游戏状态')),
            ],
        ),
    ]
