# Generated by Django 2.1.5 on 2020-02-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='组名')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('age', models.IntegerField(verbose_name='学生年龄')),
                ('genders', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=20, verbose_name='学生性别')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app01.Group')),
            ],
        ),
    ]
